### PR TITLE
Qualitative object info

### PR DESCRIPTION
**Pull request by alex-mitrevski**
Addresses https://github.com/b-it-bots/mas_perception_msgs/issues/8

Adds two messages - `NamedColor` and `NamedShape` - which define various qualitative colours and shapes respectively. Instances of both messages have been added to the `Object` message.

### CODE REVIEW

**Review by minhnh — COMMENTED** [review]
there's a standard color message [`std_msgs/ColorRGBA`](http://docs.ros.org/api/std_msgs/html/msg/ColorRGBA.html), and [`visualization_msgs/Marker`](http://docs.ros.org/melodic/api/visualization_msgs/html/msg/Marker.html) has some of these shapes (except `ELLIPSE`).

I think shape can be redefined, but color maybe is better with the default one. You can define color RGB values in code or load them from a library.

**Comment by alex-mitrevski** [comment]
> but color maybe is better with the default one. You can define color RGB values in code or load them from a library.

I don't think so. Since the standard colour message only allows numerical representation of colours, it's not suitable for the purpose intended here, namely qualitative description. If this information is not defined in a dedicated message, it would have to be defined in the code, but I think it's cleaner to have it as a message.

**Comment by minhnh** [comment]
maybe then call it `ColorName` or `NamedColor`?

**Comment by alex-mitrevski** [comment]
> maybe then call it ColorName or NamedColor?

Yeah, that's a good suggestion. I renamed it to `NamedColor`.

**Comment by minhnh** [comment]
I would also rename `Shape` as `NamedShape`, as it's serving the same purpose.

**Comment by alex-mitrevski** [comment]
Yeah, I renamed that one as well.

**Review by minhnh — APPROVED** [review]

**Review by sthoduka — APPROVED** [review]

**Pull request merged**
